---
- name: Make sure atlantis config directory exist
  file:
    name: /etc/atlantis
    state: directory

- name: Render atlantis server config
  template:
    src: config.yaml.j2
    dest: /etc/atlantis/config.yaml
    mode: "0640"

- name: Copy atlantis repo config
  copy:
    src: repos.yaml
    dest: /etc/atlantis/repos.yaml
    mode: "0644"
  notify: Restart Atlantis

- name: Run docker container
  shell: >
    docker run {{ atlantis_docker_image }}
    --config /etc/atlantis/config.yaml
    --repo-config /etc/atlantis/repos.yaml
